# Railway configuration for GTA-Style Multiplayer Game
[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "always"

# Environment variables
[env]
PORT = "8080"
NODE_ENV = "production"
GODOT_HEADLESS = "true"

# Networking configuration  
[networking]
allowedHosts = ["*"] 